version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  api:
    image: ozblech/task-manager-api:latest
    container_name: task-manager-api
    ports:
      - "3000:3000"
    # environment:
    #   - MONGODB_URL=mongodb://mongo:27017/task-manager-api
    #   - PORT=3000
    #   - JWT_SECRET=your_jwt_secret
    env_file:
      - .env
    depends_on:
      - mongo
  
  frontend:
    image: ozblech/task-app-front:latest
    container_name: task-frontend
    ports:
      - "8080:80"
    depends_on:
      - api

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
