apiVersion: v2
name: task-manager
description: A Helm chart for deploying both frontend and backend
type: application
version: 0.1.0
appVersion: "1.0"
dependencies:
  - name: mongodb
    version: 16.5.1
    repository: https://charts.bitnami.com/bitnami
