backend:
  replicaCount: 1
  image:
    repository: ozblech/task-manager-api
    tag: latest
    pullPolicy: Always
  service:
    port: 3000

frontend:
  replicaCount: 1
  image:
    repository: ozblech/task-app-front
    tag: latest
    pullPolicy: Always
  service:
    port: 80

ingress:
  enabled: true
  host: minikube.taskapp.local

service:
  port: 80

mongodb:
  architecture: standalone
  persistence:
    enabled: true
    size: 2Gi
    accessModes:
      - ReadWriteOnce
    storageClass: ""  # Leave empty to use the default storage class (like in Minikube)
    annotations:
      "helm.sh/resource-policy": keep
  auth:
    rootUser: root
    rootPassword: rootpassword
    username: appuser
    password: appuserpass
    database: myappdb
    


  


