apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-app-front
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: task-app-front
  template:
    metadata:
      labels:
        app: task-app-front
    spec:
      containers:
        - name: task-app-front
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 80
