name: PR Checks

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017
    env:
      MONGODB_URL: mongodb://localhost:27017/task-manager-api
      JWT_SECRET: thisismysecret
      SENDGRID_API_KEY: SG.TEST
      EMAIL_ACCOUNT: test@test.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run shared test action
        uses: ./.github/actions/unit-test
