name: Deploy to EKS

on:
  workflow_run:
    workflows: ["Deploy Backend"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to EKS via Helm
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

    steps:
      - name: Checkout backend repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Required to get full history and tags

      - name: Get backend image tag from Git
        id: backend_tag
        run: |
          git fetch --tags
          BACKEND_TAG=$(git describe --tags `git rev-list --tags --max-count=1` || echo "v1.0.0")
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "Created SHORT_SHA: $SHORT_SHA"
          CLEAN_TAG="${BACKEND_TAG#v}"  # Remove leading "v"
          BACKEND_IMAGE_TAG="${CLEAN_TAG}-${SHORT_SHA}"
          
          echo "BACKEND_TAG=$BACKEND_TAG" >> $GITHUB_ENV
          echo "SHORT_SHA=$SHORT_SHA" >> $GITHUB_ENV
          echo "BACKEND_IMAGE_TAG=$BACKEND_IMAGE_TAG" >> $GITHUB_ENV
          echo "Final backend image tag: $BACKEND_IMAGE_TAG"

      - name: Clone frontend repo
        uses: actions/checkout@v3
        with:
          repository: ozblech/task-app-front
          path: frontend
          fetch-depth: 0  # Required to get full history and tags

      - name: Get frontend image tag from Git
        id: frontend_tag
        run: |
          cd frontend
          git fetch --tags
          FRONTEND_TAG=$(git describe --tags `git rev-list --tags --max-count=1` || echo "v1.0.0")
          echo "Found frontend tag: $FRONTEND_TAG"
          SHORT_SHA=$(git rev-parse --short HEAD)
          echo "Found SHORT_SHA: $SHORT_SHA"
          CLEAN_TAG="${FRONTEND_TAG#v}"  # Remove leading "v"
          echo "Created CLEAN_TAG: $CLEAN_TAG"
          echo "FRONTEND_TAG=$CLEAN_TAG" >> $GITHUB_ENV
          echo "FRONTEND_IMAGE_TAG=${FRONTEND_TAG}-${SHORT_SHA}" >> $GITHUB_ENV
          echo "Found frontend tag: $FRONTEND_IMAGE_TAG"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up kubectl
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Create values-secret.yaml from GitHub Secrets
        run: |
          cat <<EOF > ./my-app/values-secret.yaml
          backend:
            env:
              MONGODB_URL: "${{ secrets.MONGODB_URL }}"
              SENDGRID_API_KEY: "${{ secrets.SENDGRID_API_KEY }}"
              EMAIL_ACCOUNT: "${{ secrets.EMAIL_ACCOUNT }}"
              JWT_SECRET: "${{ secrets.JWT_SECRET }}"
          mongodb:
            auth:
              rootPassword: "${{ secrets.MONGO_ROOT_PASSWORD }}"
              username: "${{ secrets.MONGO_USERNAME }}"
              password: "${{ secrets.MONGO_PASSWORD }}"
              database: "${{ secrets.MONGO_DATABASE }}"
          EOF
      - name: Add Bitnami repo
        run: |
          helm repo add bitnami https://charts.bitnami.com/bitnami
          helm repo update

      - name: Add ingress-nginx Helm repo
        run: |
          helm repo add ingress-nginx https://kubernetes.github.io/ingress-nginx
          helm repo update
  
      - name: Install NGINX Ingress Controller (if not already installed)
        run: |
          if ! kubectl get deployment ingress-nginx-controller -n ingress-nginx >/dev/null 2>&1; then
            helm upgrade --install ingress-nginx ingress-nginx/ingress-nginx \
              --namespace ingress-nginx --create-namespace \
              --set controller.publishService.enabled=true
          else
            echo "Ingress NGINX controller already installed."
          fi
      - name: Build Helm dependencies
        run: |
          helm dependency build ./my-app

      - name: Deploy with Helm
        run: |
          helm upgrade --install task-manager ./my-app \
            --namespace dev --create-namespace \
            -f ./my-app/values.yaml \
            -f ./my-app/values-secret.yaml
            - set backend.image.tag=${BACKEND_IMAGE_TAG} \
            - set frontend.image.tag=${FRONTEND_IMAGE_TAG} \
