name: Deploy to EKS

on:
  workflow_run:
    workflows: ["Deploy Backend"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to EKS via Helm
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      EKS_CLUSTER_NAME: ${{ secrets.EKS_CLUSTER_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set up kubectl
        run: |
          aws eks update-kubeconfig --name $EKS_CLUSTER_NAME --region $AWS_REGION

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Create values-secret.yaml from GitHub Secrets
        run: |
          cat <<EOF > ./my-app/values-secret.yaml
          backend:
            env:
              MONGODB_URL: "${{ secrets.MONGODB_URL }}"
              SENDGRID_API_KEY: "${{ secrets.SENDGRID_API_KEY }}"
              EMAIL_ACCOUNT: "${{ secrets.EMAIL_ACCOUNT }}"
              JWT_SECRET: "${{ secrets.JWT_SECRET }}"
          mongodb:
            auth:
              rootPassword: "${{ secrets.MONGO_ROOT_PASSWORD }}"
              username: "${{ secrets.MONGO_USERNAME }}"
              password: "${{ secrets.MONGO_PASSWORD }}"
              database: "${{ secrets.MONGO_DATABASE }}"
          EOF

      - name: Deploy with Helm
        run: |
          helm upgrade --install task-manager ./my-app \
            --namespace dev --create-namespace \
            -f ./my-app/values.yaml \
            -f ./my-app/values-secret.yaml
