name: Deploy Backend

on:
  push:

  
jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mongo:
        image: mongo
        ports:
          - 27017:27017

    env:
      MONGODB_URL: mongodb://localhost:27017/task-manager-api
      JWT_SECRET: thisismysecret
      SENDGRID_API_KEY: SG.TEST
      EMAIL_ACCOUNT: test@test.com

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm test
  
  build-and-push:
    runs-on: ubuntu-latest
    needs: test  # Only run if 'test' job succeeds
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and push Docker image
        run: |
          docker build -t "${{ secrets.DOCKER_USERNAME }}"/task-manager-api:latest .
          docker push "${{ secrets.DOCKER_USERNAME }}"/task-manager-api:latest
